# PLEASE DO NOT EDIT THIS FILE MANUALLY
# AND PLEASE DO NOT UPLOAD THIS FILE TO DOCKER HUB
# THIS FILE IS GENERATED BY THE CI/CD PIPELINE
# AND IS ONLY USED FOR LOCAL DEVELOPMENT
# THE ENVIRONMENT VARIABLES IS NOT PROTECTED!

# Pull lighweiht node LTS on alpine
FROM node:18-alpine AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app

COPY package.json package-lock.json ./
RUN  npm install --production

# Pull modules and build
FROM node:18-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

ENV NEXT_TELEMETRY_DISABLED 1

RUN npm run build

# Run the app on port 3000
FROM node:18-alpine AS runner
WORKDIR /app

ENV NODE_ENV production
ENV NEXT_TELEMETRY_DISABLED 1

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=builder --chown=nextjs:nodejs /app/.next ./.next
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json

USER nextjs

EXPOSE 3000

ENV PORT 3000

# Literally run the app
CMD ["npm", "start"]
